name: Latest Twitter Tweets
on:
  schedule:
    # Runs once a day because using Free tier in Rss.app
    - cron: "0 0 * * *"
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly.
permissions:
  contents: write # To write the generated contents to the readme
jobs:
  update-readme-with-twitter:
    name: Update this repo's README with latest tweets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in twitter posts
        uses: gautamkrishnar/blog-post-workflow@1.8.8
        with:
          comment_tag_name: "TWITTER"
          feed_list: "https://rss.app/feeds/P64d4euhPAXha2iv.xml"
          commit_message: "Updated with the latest tweets"
          committer_username: "twitter-bot"
          committer_email: "twitter-bot@example.com"
